import React from 'react';

class Menu extends React.Component {
  render() {
    const colors = [
    '#ace',
    '#aceace',
    '#acefff',
    '#999ace',
    '#ace999',
    '#ace000',
    '#000ace',
    '#ffface',
    '#acefff',
    '#999',
    '#ffffff',
    '#090909',
    '#9a9c9e',
    '#a9c9e9',
    '#aceeca',
    '#ecaace',
    '#555ace',
    '#ace555',
    '#acefab',
    '#fabace',
    '#ace',
    '#999',
    '#0a0c0e',
    '#a0c0e0',
    '#abcdef',
    '#012345',
    '#a1c3e5',
    '#fedcba',
    '#543210',
    '#000ace',
    '#111ace',
    '#222ace',
    '#333ace',
    '#444ace',
    '#555ace',
    '#666ace',
    '#777ace',
    '#888ace',
    '#999ace',
    '#aaaace',
    '#bbbace',
    '#cccace',
    '#dddace',
    '#eeeace',
    '#ffface',
    '#ace000',
    '#ace111',
    '#ace222',
    '#ace333',
    '#ace444',
    '#ace555',
    '#ace666',
    '#ace777',
    '#ace888',
    '#ace999',
    '#aceaaa',
    '#acebbb',
    '#aceccc',
    '#aceddd',
    '#aceeee',
    '#acefff',
    '#123ace',
    '#ace123',
    '#badace',
    '#acebad',
    '#ace',
    '#ace',
    '#ace',
    '#ace',
    '#57A6E5',
    '#ba11ed',
    '#ffaded',
    '#0faded',
    '#faded0',
    '#9faded',
    '#fade99',
    '#99fade',
    '#beeace',
    '#acefed',
    '#bada55',
    '#facade',
    '#deface',
    '#c0ffee',
    '#dabbed',
    '#d00dad',
    '#dec0de',
    '#b1ade5',
    '#1e5b05',
    '#00d1e5',
    '#d00d1e',
    '#f001ed'
    ];
    return (
      colors.map((e, i) => {
        return (<div style={{background:e, padding:20 + 'px', font:2 + 'pt'}} key={i}>{e}</div>)
      })
    );
  }
}

export default Menu;
